var searchData=
[
  ['l1norm_11228',['L1Norm',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1L1Norm.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['lagrangeequidistant_11229',['LagrangeEquidistant',['../classPolynomials_1_1LagrangeEquidistant.html',1,'Polynomials']]],
  ['lambdaoptimizer_11230',['LambdaOptimizer',['../structDifferentiation_1_1SD_1_1internal_1_1LambdaOptimizer.html',1,'Differentiation::SD::internal']]],
  ['lapackfullmatrix_11231',['LAPACKFullMatrix',['../classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20double_20_3e_11232',['LAPACKFullMatrix&lt; double &gt;',['../classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20number_20_3e_11233',['LAPACKFullMatrix&lt; Number &gt;',['../classLAPACKFullMatrix.html',1,'']]],
  ['laplaceoperator_11234',['LaplaceOperator',['../classMatrixFreeOperators_1_1LaplaceOperator.html',1,'MatrixFreeOperators']]],
  ['legendre_11235',['Legendre',['../classFESeries_1_1Legendre.html',1,'FESeries::Legendre&lt; dim, spacedim &gt;'],['../classPolynomials_1_1Legendre.html',1,'Polynomials::Legendre']]],
  ['levelequalto_11236',['LevelEqualTo',['../classIteratorFilters_1_1LevelEqualTo.html',1,'IteratorFilters']]],
  ['line_11237',['Line',['../structDynamicSparsityPattern_1_1Line.html',1,'DynamicSparsityPattern']]],
  ['linearindexiterator_11238',['LinearIndexIterator',['../classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_2c_20accessor_20_3e_11239',['LinearIndexIterator&lt; Iterator, Accessor &gt;',['../classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_2c_20accessor_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_20_3e_11240',['LinearIndexIterator&lt; Iterator&lt; TableType, Constness, storage_order &gt;, Accessor&lt; TableType, Constness, storage_order &gt; &gt;',['../classLinearIndexIterator.html',1,'']]],
  ['linearoperator_11241',['LinearOperator',['../classLinearOperator.html',1,'']]],
  ['linearoperator_3c_20range_2c_20domain_2c_20blockpayload_3a_3ablocktype_20_3e_11242',['LinearOperator&lt; Range, Domain, BlockPayload::BlockType &gt;',['../classLinearOperator.html',1,'']]],
  ['linearsolvercontent_11243',['LinearSolverContent',['../structSUNDIALS_1_1internal_1_1LinearSolverContent.html',1,'SUNDIALS::internal']]],
  ['linearsolverwrapper_11244',['LinearSolverWrapper',['../classSUNDIALS_1_1internal_1_1LinearSolverWrapper.html',1,'SUNDIALS::internal']]],
  ['linfty_11245',['LInfty',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1LInfty.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['list_11246',['List',['../classPatterns_1_1List.html',1,'Patterns']]],
  ['lobatto_11247',['Lobatto',['../classPolynomials_1_1Lobatto.html',1,'Polynomials']]],
  ['localintegrator_11248',['LocalIntegrator',['../classMeshWorker_1_1LocalIntegrator.html',1,'MeshWorker']]],
  ['locallyownedcell_11249',['LocallyOwnedCell',['../classIteratorFilters_1_1LocallyOwnedCell.html',1,'IteratorFilters']]],
  ['locallyownedlevelcell_11250',['LocallyOwnedLevelCell',['../classIteratorFilters_1_1LocallyOwnedLevelCell.html',1,'IteratorFilters']]],
  ['localresults_11251',['LocalResults',['../classMeshWorker_1_1LocalResults.html',1,'MeshWorker']]],
  ['localresults_3c_20double_20_3e_11252',['LocalResults&lt; double &gt;',['../classMeshWorker_1_1LocalResults.html',1,'MeshWorker']]],
  ['logstream_11253',['LogStream',['../classLogStream.html',1,'']]],
  ['loopcontrol_11254',['LoopControl',['../classMeshWorker_1_1LoopControl.html',1,'MeshWorker']]],
  ['lowstoragerungekutta_11255',['LowStorageRungeKutta',['../classTimeStepping_1_1LowStorageRungeKutta.html',1,'TimeStepping']]],
  ['lsingularityfunction_11256',['LSingularityFunction',['../classFunctions_1_1LSingularityFunction.html',1,'Functions']]],
  ['lsingularitygradfunction_11257',['LSingularityGradFunction',['../classFunctions_1_1LSingularityGradFunction.html',1,'Functions']]]
];
