var searchData=
[
  ['barycentricpolynomial_10545',['BarycentricPolynomial',['../classBarycentricPolynomial.html',1,'']]],
  ['barycentricpolynomials_10546',['BarycentricPolynomials',['../classBarycentricPolynomials.html',1,'']]],
  ['barycentricpolynomials_3c_201_20_3e_10547',['BarycentricPolynomials&lt; 1 &gt;',['../classBarycentricPolynomials.html',1,'']]],
  ['barycentricpolynomials_3c_202_20_3e_10548',['BarycentricPolynomials&lt; 2 &gt;',['../classBarycentricPolynomials.html',1,'']]],
  ['base_10549',['Base',['../classinternal_1_1MatrixFreeFunctions_1_1VectorDataExchange_1_1Base.html',1,'internal::MatrixFreeFunctions::VectorDataExchange::Base'],['../classMatrixFreeOperators_1_1Base.html',1,'MatrixFreeOperators::Base&lt; dim, VectorType, VectorizedArrayType &gt;']]],
  ['base_3c_20dim_2c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20double_20_3e_2c_20vectorizedarray_3c_20typename_20vectortype_3a_3avalue_5ftype_20_3e_20_3e_10550',['Base&lt; dim, LinearAlgebra::distributed::Vector&lt; double &gt;, VectorizedArray&lt; typename VectorType::value_type &gt; &gt;',['../classMatrixFreeOperators_1_1Base.html',1,'MatrixFreeOperators']]],
  ['baseiterator_10551',['BaseIterator',['../classBaseIterator.html',1,'']]],
  ['baseqr_10552',['BaseQR',['../classBaseQR.html',1,'']]],
  ['batchoptimizer_10553',['BatchOptimizer',['../classDifferentiation_1_1SD_1_1BatchOptimizer.html',1,'Differentiation::SD']]],
  ['bessel1_10554',['Bessel1',['../classFunctions_1_1Bessel1.html',1,'Functions']]],
  ['binop_5faddition_10555',['Binop_Addition',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Addition.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5faddition_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_10556',['Binop_Addition&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Addition_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmax_10557',['Binop_Max',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Max.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmax_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_10558',['Binop_Max&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Max_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmin_10559',['Binop_Min',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Min.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmin_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_10560',['Binop_Min&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Min_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fsubtraction_10561',['Binop_Subtraction',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Subtraction.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fsubtraction_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e_10562',['Binop_Subtraction&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Subtraction_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['blockdynamicsparsitypattern_10563',['BlockDynamicSparsityPattern',['../classBlockDynamicSparsityPattern.html',1,'']]],
  ['blockindices_10564',['BlockIndices',['../classBlockIndices.html',1,'']]],
  ['blockinfo_10565',['BlockInfo',['../classBlockInfo.html',1,'']]],
  ['blocklinearoperator_10566',['BlockLinearOperator',['../classBlockLinearOperator.html',1,'']]],
  ['blockmask_10567',['BlockMask',['../classBlockMask.html',1,'']]],
  ['blockmatrixbase_10568',['BlockMatrixBase',['../classBlockMatrixBase.html',1,'']]],
  ['blockmatrixbase_3c_20sparsematrix_20_3e_10569',['BlockMatrixBase&lt; SparseMatrix &gt;',['../classBlockMatrixBase.html',1,'']]],
  ['blockmatrixbase_3c_20sparsematrix_3c_20number_20_3e_20_3e_10570',['BlockMatrixBase&lt; SparseMatrix&lt; number &gt; &gt;',['../classBlockMatrixBase.html',1,'']]],
  ['blocksparsematrix_10571',['BlockSparseMatrix',['../classBlockSparseMatrix.html',1,'BlockSparseMatrix&lt; number &gt;'],['../classPETScWrappers_1_1MPI_1_1BlockSparseMatrix.html',1,'PETScWrappers::MPI::BlockSparseMatrix'],['../classTrilinosWrappers_1_1BlockSparseMatrix.html',1,'TrilinosWrappers::BlockSparseMatrix']]],
  ['blocksparsematrixez_10572',['BlockSparseMatrixEZ',['../classBlockSparseMatrixEZ.html',1,'']]],
  ['blocksparsitypattern_10573',['BlockSparsityPattern',['../classBlockSparsityPattern.html',1,'BlockSparsityPattern'],['../classTrilinosWrappers_1_1BlockSparsityPattern.html',1,'TrilinosWrappers::BlockSparsityPattern']]],
  ['blocksparsitypatternbase_10574',['BlockSparsityPatternBase',['../classBlockSparsityPatternBase.html',1,'']]],
  ['blocksparsitypatternbase_3c_20dynamicsparsitypattern_20_3e_10575',['BlockSparsityPatternBase&lt; DynamicSparsityPattern &gt;',['../classBlockSparsityPatternBase.html',1,'']]],
  ['blocksparsitypatternbase_3c_20sparsitypattern_20_3e_10576',['BlockSparsityPatternBase&lt; SparsityPattern &gt;',['../classBlockSparsityPatternBase.html',1,'']]],
  ['blockvector_10577',['BlockVector',['../classBlockVector.html',1,'BlockVector&lt; Number &gt;'],['../classLinearAlgebra_1_1distributed_1_1BlockVector.html',1,'LinearAlgebra::distributed::BlockVector&lt; Number &gt;'],['../classPETScWrappers_1_1MPI_1_1BlockVector.html',1,'PETScWrappers::MPI::BlockVector'],['../classTrilinosWrappers_1_1MPI_1_1BlockVector.html',1,'TrilinosWrappers::MPI::BlockVector']]],
  ['blockvector_3c_20number_20_3e_10578',['BlockVector&lt; number &gt;',['../classBlockVector.html',1,'']]],
  ['blockvectorbase_10579',['BlockVectorBase',['../classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20mpi_3a_3avector_20_3e_10580',['BlockVectorBase&lt; MPI::Vector &gt;',['../classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20vector_20_3e_10581',['BlockVectorBase&lt; Vector &gt;',['../classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20vector_3c_20number_20_3e_20_3e_10582',['BlockVectorBase&lt; Vector&lt; Number &gt; &gt;',['../classBlockVectorBase.html',1,'']]],
  ['body_10583',['Body',['../structparallel_1_1internal_1_1Body.html',1,'parallel::internal']]],
  ['bool_10584',['Bool',['../classPatterns_1_1Bool.html',1,'Patterns']]],
  ['boolstorage_10585',['BoolStorage',['../structinternal_1_1TemplateConstraints_1_1BoolStorage.html',1,'internal::TemplateConstraints']]],
  ['boundaryormaterialid_10586',['BoundaryOrMaterialId',['../structinternal_1_1TriangulationImplementation_1_1TriaObjects_1_1BoundaryOrMaterialId.html',1,'internal::TriangulationImplementation::TriaObjects']]],
  ['boundingbox_10587',['BoundingBox',['../classBoundingBox.html',1,'']]],
  ['boundingbox_3c_200_2c_20number_20_3e_10588',['BoundingBox&lt; 0, Number &gt;',['../classBoundingBox_3_010_00_01Number_01_4.html',1,'']]],
  ['boundingbox_3c_203_2c_20float_20_3e_10589',['BoundingBox&lt; 3, float &gt;',['../classBoundingBox.html',1,'']]],
  ['boundingbox_3c_20boost_3a_3ageometry_3a_3adimension_3c_20box_20_3e_3a_3avalue_20_3e_10590',['BoundingBox&lt; boost::geometry::dimension&lt; Box &gt;::value &gt;',['../classBoundingBox.html',1,'']]],
  ['boundingboxdataout_10591',['BoundingBoxDataOut',['../classBoundingBoxDataOut.html',1,'']]],
  ['boundingboxintersectpredicate_10592',['BoundingBoxIntersectPredicate',['../classArborXWrappers_1_1BoundingBoxIntersectPredicate.html',1,'ArborXWrappers']]],
  ['boundingboxnearestpredicate_10593',['BoundingBoxNearestPredicate',['../classArborXWrappers_1_1BoundingBoxNearestPredicate.html',1,'ArborXWrappers']]],
  ['boundingboxpredicate_10594',['BoundingBoxPredicate',['../classArborXWrappers_1_1BoundingBoxPredicate.html',1,'ArborXWrappers']]],
  ['bvh_10595',['BVH',['../classArborXWrappers_1_1BVH.html',1,'ArborXWrappers']]]
];
